# Generated by Django 3.2.14 on 2024-01-12 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=255)),
                ('Blog_category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetable', 'Vegetable'), ('fertilizers', 'fertilizers'), ('other', 'other')], max_length=255)),
                ('Blog_Discription', models.CharField(max_length=1000)),
                ('Disease', models.CharField(max_length=255)),
                ('Disease_Discription', models.CharField(max_length=1000)),
                ('Symptoms', models.CharField(max_length=255)),
                ('Symptoms_Discription', models.CharField(max_length=1000)),
                ('Remedy', models.CharField(max_length=1000)),
                ('Other', models.CharField(max_length=1000)),
                ('Blog_image', models.FileField(upload_to='blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=244)),
                ('Product_Category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetable', 'Vegetable'), ('fertilizers', 'fertilizers'), ('other', 'other')], max_length=255)),
                ('Product_price', models.IntegerField()),
                ('Product_Discription', models.CharField(max_length=1000)),
                ('Product_Stock', models.IntegerField(blank=True, null=True)),
                ('Product_Image', models.FileField(upload_to='Customer_products')),
                ('Product_Location', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('noofReviews', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('TotalPrice', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('TotalPrice', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
