# Generated by Django 3.2.14 on 2024-01-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Location',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
