# Generated by Django 5.0 on 2024-01-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=255)),
                ('Blog_category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetable', 'Vegetable'), ('fertilizers', 'fertilizers'), ('other', 'other')], max_length=255)),
                ('Blog_Discription', models.CharField(max_length=1000)),
                ('Blog_image', models.FileField(upload_to='blogs')),
            ],
        ),
    ]
